# Generated by Django 5.2.3 on 2025-06-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
