# Generated by Django 5.2.3 on 2025-06-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
